services:
  news-hub-prod:
    image: webcrunch/news-hub:latest
    container_name: news-hub-production
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"

      # --- ROUTING ---
      - "traefik.http.routers.newshub.rule=Host(`jarllindquist.com`) && PathPrefix(`/news`)"
      - "traefik.http.routers.newshub.entrypoints=websecure"
      - "traefik.http.routers.newshub.tls.certresolver=myresolver"
      - "traefik.http.routers.newshub.priority=10"

      # --- SERVICE ---
      - "traefik.http.services.newshub.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
