server {
    listen 80;
    server_name localhost;

    location /news {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Detta tvingar Nginx att skicka routerna till index.html istället för att kasta 404
        try_files $uri $uri/ /news/index.html;
    }

    # Hantera felmeddelanden
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}